folke/tokyonight.nvim

- lua/tokyonight/theme.lua
For groups mainly used for comments
> Improve tree-sitter support

- extras/tmux_tokyonight_day.tmux
- extras/tmux_tokyonight_night.tmux
- extras/tmux_tokyonight_storm.tmux
- lua/tokyonight/extra/init.lua
- lua/tokyonight/extra/tmux.lua
Same as https://github.com/folke/tokyonight.nvim/pull/51 but using the lua extra util so we get all color themes
Made it match lualine normal mode colors
> feat: add tmux themes

- README.md
- lua/tokyonight/theme.lua
Hi I updated this theme to have a better support for lspsaga and add Fern support. (#55 )
Lsp Saga colors
Fern colors
> feat: added fern and lspsaga colors

- lua/tokyonight/util.lua
https://user-images.githubusercontent.com/24286590/127281654-0b1d5ad9-ef60-4555-a75d-a92aaea97c38.mp4
> nested & `NONE` colors override added

- extras/kitty_tokyonight_day.conf
- extras/kitty_tokyonight_night.conf
- extras/kitty_tokyonight_storm.conf
- lua/tokyonight/extra/init.lua
- lua/tokyonight/extra/kitty.lua
Makes them suitable for inclusion in
https://github.com/kovidgoyal/kitty-themes
> Cleanup kitty themes

- lua/tokyonight/theme.lua
I don't know if you agree with my choices, but adding the other item kinds. 
#124
> Adding more cmp item kinds

- lua/tokyonight/theme.lua
This is a follow up of PR #137. This applies sensible defaults for both when background set to transparent or not.
previous PR introduced some unwanted behavior as pointed out [here](https://github.com/folke/tokyonight.nvim/pull/137#issuecomment-1016239546)
> Improved telescope theme for non transparent mode.

- lua/tokyonight/theme.lua
> fix comment

- README.md
- doc/tokyonight.nvim.txt
wrong operator in doc when set some attribute/operator
> update wrong operator in doc

- lua/tokyonight/theme.lua
> Add color for folder icon in NvimTree and remove ugly background

- lua/tokyonight/theme.lua
> feat: add support for ts-rainbow

- lua/tokyonight/colors.lua
- lua/tokyonight/util.lua
I noticed some inconsistency in colors case, this PR makes them all lowercase.
`extras` config would need to be regenerated, let me know if you'd like me to make re-generate them.
> fix: colors case consistency

- README.md
Added missing bracket to example setup options in README.
> Added missing bracket to README

- lua/tokyonight/theme.lua
Apply `transparent` option also to `FoldColumn`
> feat(theme): apply transparent to FoldColumn

- extras/lua/tokyonight_day.lua
- extras/lua/tokyonight_moon.lua
- extras/lua/tokyonight_night.lua
- extras/lua/tokyonight_storm.lua
- lua/tokyonight/theme.lua
see https://github.com/lukas-reineke/indent-blankline.nvim/issues/72
> fix: indent-blankline highlight groups nocombine

- lua/lualine/themes/tokyonight.lua
I choose green1 so it similar to insert mode green.
> feat: add lualine terminal mode

- README.md
- lua/barbecue/theme/tokyonight.lua
[barbecue.nvim](https://github.com/utilyre/barbecue.nvim) is a VS Code like winbar for Neovim. This is how it looks like
> Added barbecue support

- lua/tokyonight/config.lua
> Fix some typos in comments

- lua/tokyonight/theme.lua
> feat: Improve night barbar

- lua/tokyonight/theme.lua
This way the color of GitGutter line number is consistent with the color of GitGutter sign
> Set highlight of GitGutterLineNr

- lua/tokyonight/extra/dunst.lua
- lua/tokyonight/extra/init.lua
Added TokyoNight colorscheme for [dunst](https://dunst-project.org/) notification daemon.
> add colors for dunst

- lua/tokyonight/extra/gitui.lua
- lua/tokyonight/extra/init.lua
> feat: add gitui theme

- README.md
> This is how you do it: you sit down at the keyboard and you put one word after another until its done. It's that easy, and that hard.
>
> - Neil Gaiman
The initial three commits in this PR offer objective quality enhancements, while the last one leans towards a more subjective improvement. I aimed to enhance the overall writing quality while maintaining the original style.
Let me know if any adjustments are needed.
> docs(readme): improve overall quality

- lua/tokyonight/theme.lua
> feat(markdown treesitter support)

- README.md
- lua/tokyonight/extra/helix.lua
- lua/tokyonight/extra/init.lua
- lua/tokyonight/theme.lua
Hello! First of all, a big thank you for this theme, it's absolutely gorgeous!
I'm currently trying Helix editor and their current Tokyonight themes weren't as good as this one, so took some time to add the extras here. My code basically translates Helix scopes to neovim ones. I did a first rough job, it'll certainly need some updates over time. It's my first time writing Lua, so any improvement suggestions are more than welcome. :)
I also updated the `README.md` with the CI command to generate the extras, it took me some time to realize that the provided command expects me to work on the installed plugin. It's more convenient for me not to.
> feat: Add Helix extras

- README.md
- lua/tokyonight/extra/dunst.lua
- lua/tokyonight/extra/init.lua
- lua/tokyonight/extra/lazygit.lua
Add lazygit extra. Inspired from LazyVim lazygit theme config.
Also fixed a typo in dunst. I hope that's okay with you that it's in the same PR.
> feat(extras): add lazygit

- lua/tokyonight/extra/init.lua
Got the extension wrong in the initial PR, oops.
> fix(extras): correct lazygit extension

- lua/tokyonight/extra/helix.lua
> helix: fix markup broken generated values

- lua/tokyonight/extra/fish.lua
- lua/tokyonight/extra/fish_themes.lua
Colorize `fish_color_option` in fish
- Before
- After
None
Attached above
> feat(fish): add `fish_color_option`

- extras/lua/tokyonight_day.lua
- extras/lua/tokyonight_moon.lua
- extras/lua/tokyonight_night.lua
- extras/lua/tokyonight_storm.lua
- lua/tokyonight/groups/cmp.lua
Add `CmpItemKindSupermaven` support for plugin [supermaven-nvim](https://github.com/supermaven-inc/supermaven-nvim) like copilot and codeium.
> feat(supermaven): add support for supermaven-nvim

- extras/eza/README.md
- extras/eza/tokyonight.yml
Took a shot at creating a Tokyonight theme for `eza`.
> feat(extras): add eza theme

- lua/tokyonight/extra/yazi.lua
This is a PR for the yazi v0.4 theme, as it changes some of the TOML config keys. I also adjust some values for better UI.
> feat(extras): update for yazi 0.4
